# Generated by Django 4.2.25 on 2025-10-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habr_app', '0003_userlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
